apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teamcity-data-pvc
  namespace: teamcity
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teamcity-logs-pvc
  namespace: teamcity
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path