apiVersion: v1
kind: PersistentVolume
metadata:
  name: teamcity-data-pv
  namespace: teamcity
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/joshheyse/code/teamcity-k8s/storage/teamcity/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: teamcity-logs-pv
  namespace: teamcity
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/joshheyse/code/teamcity-k8s/storage/teamcity/logs"