apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: teamcity-ingress
  namespace: teamcity
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: teamcity-server-service
                port:
                  number: 8111
---
apiVersion: v1
kind: Service
metadata:
  name: teamcity-server-service
  namespace: teamcity
spec:
  selector:
    app: teamcity-server
  type: ClusterIP
  ports:
  - port: 8111
    targetPort: 8111
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teamcity-server
  namespace: teamcity
spec:
  selector:
    matchLabels:
      app: teamcity-server
  template:
    metadata:
      labels:
        app: teamcity-server
    spec:
      containers:
      - name: teamcity-server
        image: teamcity-server:EAP-linux-arm64
        resources:
          limits:
            memory: "4Gi"
            cpu: "2000m"
        ports:
        - containerPort: 8111
        volumeMounts:
          - name: teamcity-data-volume
            mountPath: /data/teamcity_server/datadir
          - name: teamcity-logs-volume
            mountPath: /opt/teamcity/logs
      volumes:
        - name: teamcity-data-volume
          persistentVolumeClaim:
            claimName: teamcity-data-pvc
        - name: teamcity-logs-volume
          persistentVolumeClaim:
            claimName: teamcity-logs-pvc